// Code generated by protoc-gen-go. DO NOT EDIT.
// source: reporter.proto

package reporter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Discovery
type DiscoverRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscoverRequest) Reset()         { *m = DiscoverRequest{} }
func (m *DiscoverRequest) String() string { return proto.CompactTextString(m) }
func (*DiscoverRequest) ProtoMessage()    {}
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_reporter_41a5be73b7b1da2b, []int{0}
}
func (m *DiscoverRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoverRequest.Unmarshal(m, b)
}
func (m *DiscoverRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoverRequest.Marshal(b, m, deterministic)
}
func (dst *DiscoverRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoverRequest.Merge(dst, src)
}
func (m *DiscoverRequest) XXX_Size() int {
	return xxx_messageInfo_DiscoverRequest.Size(m)
}
func (m *DiscoverRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoverRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoverRequest proto.InternalMessageInfo

type DiscoverResponse struct {
	AverageNames            []string `protobuf:"bytes,1,rep,name=AverageNames,proto3" json:"AverageNames,omitempty"`
	AveragePerDurationNames []string `protobuf:"bytes,2,rep,name=AveragePerDurationNames,proto3" json:"AveragePerDurationNames,omitempty"`
	CounterNames            []string `protobuf:"bytes,3,rep,name=CounterNames,proto3" json:"CounterNames,omitempty"`
	CounterPerDurationNames []string `protobuf:"bytes,4,rep,name=CounterPerDurationNames,proto3" json:"CounterPerDurationNames,omitempty"`
	SumNames                []string `protobuf:"bytes,5,rep,name=SumNames,proto3" json:"SumNames,omitempty"`
	SumPerDurationNames     []string `protobuf:"bytes,6,rep,name=SumPerDurationNames,proto3" json:"SumPerDurationNames,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *DiscoverResponse) Reset()         { *m = DiscoverResponse{} }
func (m *DiscoverResponse) String() string { return proto.CompactTextString(m) }
func (*DiscoverResponse) ProtoMessage()    {}
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_reporter_41a5be73b7b1da2b, []int{1}
}
func (m *DiscoverResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoverResponse.Unmarshal(m, b)
}
func (m *DiscoverResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoverResponse.Marshal(b, m, deterministic)
}
func (dst *DiscoverResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoverResponse.Merge(dst, src)
}
func (m *DiscoverResponse) XXX_Size() int {
	return xxx_messageInfo_DiscoverResponse.Size(m)
}
func (m *DiscoverResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoverResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoverResponse proto.InternalMessageInfo

func (m *DiscoverResponse) GetAverageNames() []string {
	if m != nil {
		return m.AverageNames
	}
	return nil
}

func (m *DiscoverResponse) GetAveragePerDurationNames() []string {
	if m != nil {
		return m.AveragePerDurationNames
	}
	return nil
}

func (m *DiscoverResponse) GetCounterNames() []string {
	if m != nil {
		return m.CounterNames
	}
	return nil
}

func (m *DiscoverResponse) GetCounterPerDurationNames() []string {
	if m != nil {
		return m.CounterPerDurationNames
	}
	return nil
}

func (m *DiscoverResponse) GetSumNames() []string {
	if m != nil {
		return m.SumNames
	}
	return nil
}

func (m *DiscoverResponse) GetSumPerDurationNames() []string {
	if m != nil {
		return m.SumPerDurationNames
	}
	return nil
}

// Requesting a metric by name
type NameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameRequest) Reset()         { *m = NameRequest{} }
func (m *NameRequest) String() string { return proto.CompactTextString(m) }
func (*NameRequest) ProtoMessage()    {}
func (*NameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_reporter_41a5be73b7b1da2b, []int{2}
}
func (m *NameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameRequest.Unmarshal(m, b)
}
func (m *NameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameRequest.Marshal(b, m, deterministic)
}
func (dst *NameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameRequest.Merge(dst, src)
}
func (m *NameRequest) XXX_Size() int {
	return xxx_messageInfo_NameRequest.Size(m)
}
func (m *NameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NameRequest proto.InternalMessageInfo

func (m *NameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Responding to an average
type AverageResponse struct {
	Average              float64  `protobuf:"fixed64,1,opt,name=Average,proto3" json:"Average,omitempty"`
	N                    int64    `protobuf:"varint,2,opt,name=N,proto3" json:"N,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AverageResponse) Reset()         { *m = AverageResponse{} }
func (m *AverageResponse) String() string { return proto.CompactTextString(m) }
func (*AverageResponse) ProtoMessage()    {}
func (*AverageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_reporter_41a5be73b7b1da2b, []int{3}
}
func (m *AverageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AverageResponse.Unmarshal(m, b)
}
func (m *AverageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AverageResponse.Marshal(b, m, deterministic)
}
func (dst *AverageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AverageResponse.Merge(dst, src)
}
func (m *AverageResponse) XXX_Size() int {
	return xxx_messageInfo_AverageResponse.Size(m)
}
func (m *AverageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AverageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AverageResponse proto.InternalMessageInfo

func (m *AverageResponse) GetAverage() float64 {
	if m != nil {
		return m.Average
	}
	return 0
}

func (m *AverageResponse) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

// Responding to an average per duration
type AveragePerDurationResponse struct {
	Average              float64              `protobuf:"fixed64,1,opt,name=Average,proto3" json:"Average,omitempty"`
	N                    int64                `protobuf:"varint,2,opt,name=N,proto3" json:"N,omitempty"`
	Until                *timestamp.Timestamp `protobuf:"bytes,3,opt,name=Until,proto3" json:"Until,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AveragePerDurationResponse) Reset()         { *m = AveragePerDurationResponse{} }
func (m *AveragePerDurationResponse) String() string { return proto.CompactTextString(m) }
func (*AveragePerDurationResponse) ProtoMessage()    {}
func (*AveragePerDurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_reporter_41a5be73b7b1da2b, []int{4}
}
func (m *AveragePerDurationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AveragePerDurationResponse.Unmarshal(m, b)
}
func (m *AveragePerDurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AveragePerDurationResponse.Marshal(b, m, deterministic)
}
func (dst *AveragePerDurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AveragePerDurationResponse.Merge(dst, src)
}
func (m *AveragePerDurationResponse) XXX_Size() int {
	return xxx_messageInfo_AveragePerDurationResponse.Size(m)
}
func (m *AveragePerDurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AveragePerDurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AveragePerDurationResponse proto.InternalMessageInfo

func (m *AveragePerDurationResponse) GetAverage() float64 {
	if m != nil {
		return m.Average
	}
	return 0
}

func (m *AveragePerDurationResponse) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *AveragePerDurationResponse) GetUntil() *timestamp.Timestamp {
	if m != nil {
		return m.Until
	}
	return nil
}

type CounterResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CounterResponse) Reset()         { *m = CounterResponse{} }
func (m *CounterResponse) String() string { return proto.CompactTextString(m) }
func (*CounterResponse) ProtoMessage()    {}
func (*CounterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_reporter_41a5be73b7b1da2b, []int{5}
}
func (m *CounterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CounterResponse.Unmarshal(m, b)
}
func (m *CounterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CounterResponse.Marshal(b, m, deterministic)
}
func (dst *CounterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CounterResponse.Merge(dst, src)
}
func (m *CounterResponse) XXX_Size() int {
	return xxx_messageInfo_CounterResponse.Size(m)
}
func (m *CounterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CounterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CounterResponse proto.InternalMessageInfo

func (m *CounterResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CounterPerDurationResponse struct {
	Count                int64                `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	Until                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=Until,proto3" json:"Until,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CounterPerDurationResponse) Reset()         { *m = CounterPerDurationResponse{} }
func (m *CounterPerDurationResponse) String() string { return proto.CompactTextString(m) }
func (*CounterPerDurationResponse) ProtoMessage()    {}
func (*CounterPerDurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_reporter_41a5be73b7b1da2b, []int{6}
}
func (m *CounterPerDurationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CounterPerDurationResponse.Unmarshal(m, b)
}
func (m *CounterPerDurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CounterPerDurationResponse.Marshal(b, m, deterministic)
}
func (dst *CounterPerDurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CounterPerDurationResponse.Merge(dst, src)
}
func (m *CounterPerDurationResponse) XXX_Size() int {
	return xxx_messageInfo_CounterPerDurationResponse.Size(m)
}
func (m *CounterPerDurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CounterPerDurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CounterPerDurationResponse proto.InternalMessageInfo

func (m *CounterPerDurationResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *CounterPerDurationResponse) GetUntil() *timestamp.Timestamp {
	if m != nil {
		return m.Until
	}
	return nil
}

type SumResponse struct {
	Sum                  float64  `protobuf:"fixed64,1,opt,name=Sum,proto3" json:"Sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_reporter_41a5be73b7b1da2b, []int{7}
}
func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (dst *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(dst, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetSum() float64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

type SumPerDurationResponse struct {
	Sum                  float64              `protobuf:"fixed64,1,opt,name=Sum,proto3" json:"Sum,omitempty"`
	Until                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=Until,proto3" json:"Until,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SumPerDurationResponse) Reset()         { *m = SumPerDurationResponse{} }
func (m *SumPerDurationResponse) String() string { return proto.CompactTextString(m) }
func (*SumPerDurationResponse) ProtoMessage()    {}
func (*SumPerDurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_reporter_41a5be73b7b1da2b, []int{8}
}
func (m *SumPerDurationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumPerDurationResponse.Unmarshal(m, b)
}
func (m *SumPerDurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumPerDurationResponse.Marshal(b, m, deterministic)
}
func (dst *SumPerDurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumPerDurationResponse.Merge(dst, src)
}
func (m *SumPerDurationResponse) XXX_Size() int {
	return xxx_messageInfo_SumPerDurationResponse.Size(m)
}
func (m *SumPerDurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumPerDurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumPerDurationResponse proto.InternalMessageInfo

func (m *SumPerDurationResponse) GetSum() float64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *SumPerDurationResponse) GetUntil() *timestamp.Timestamp {
	if m != nil {
		return m.Until
	}
	return nil
}

func init() {
	proto.RegisterType((*DiscoverRequest)(nil), "reporter.DiscoverRequest")
	proto.RegisterType((*DiscoverResponse)(nil), "reporter.DiscoverResponse")
	proto.RegisterType((*NameRequest)(nil), "reporter.NameRequest")
	proto.RegisterType((*AverageResponse)(nil), "reporter.AverageResponse")
	proto.RegisterType((*AveragePerDurationResponse)(nil), "reporter.AveragePerDurationResponse")
	proto.RegisterType((*CounterResponse)(nil), "reporter.CounterResponse")
	proto.RegisterType((*CounterPerDurationResponse)(nil), "reporter.CounterPerDurationResponse")
	proto.RegisterType((*SumResponse)(nil), "reporter.SumResponse")
	proto.RegisterType((*SumPerDurationResponse)(nil), "reporter.SumPerDurationResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReporterClient is the client API for Reporter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReporterClient interface {
	Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error)
	Average(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*AverageResponse, error)
	AveragePerDuration(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*AveragePerDurationResponse, error)
	Counter(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*CounterResponse, error)
	CounterPerDuration(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*CounterPerDurationResponse, error)
	Sum(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*SumResponse, error)
	SumPerDuration(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*SumPerDurationResponse, error)
}

type reporterClient struct {
	cc *grpc.ClientConn
}

func NewReporterClient(cc *grpc.ClientConn) ReporterClient {
	return &reporterClient{cc}
}

func (c *reporterClient) Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error) {
	out := new(DiscoverResponse)
	err := c.cc.Invoke(ctx, "/reporter.Reporter/Discover", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterClient) Average(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*AverageResponse, error) {
	out := new(AverageResponse)
	err := c.cc.Invoke(ctx, "/reporter.Reporter/Average", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterClient) AveragePerDuration(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*AveragePerDurationResponse, error) {
	out := new(AveragePerDurationResponse)
	err := c.cc.Invoke(ctx, "/reporter.Reporter/AveragePerDuration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterClient) Counter(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*CounterResponse, error) {
	out := new(CounterResponse)
	err := c.cc.Invoke(ctx, "/reporter.Reporter/Counter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterClient) CounterPerDuration(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*CounterPerDurationResponse, error) {
	out := new(CounterPerDurationResponse)
	err := c.cc.Invoke(ctx, "/reporter.Reporter/CounterPerDuration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterClient) Sum(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/reporter.Reporter/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterClient) SumPerDuration(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*SumPerDurationResponse, error) {
	out := new(SumPerDurationResponse)
	err := c.cc.Invoke(ctx, "/reporter.Reporter/SumPerDuration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReporterServer is the server API for Reporter service.
type ReporterServer interface {
	Discover(context.Context, *DiscoverRequest) (*DiscoverResponse, error)
	Average(context.Context, *NameRequest) (*AverageResponse, error)
	AveragePerDuration(context.Context, *NameRequest) (*AveragePerDurationResponse, error)
	Counter(context.Context, *NameRequest) (*CounterResponse, error)
	CounterPerDuration(context.Context, *NameRequest) (*CounterPerDurationResponse, error)
	Sum(context.Context, *NameRequest) (*SumResponse, error)
	SumPerDuration(context.Context, *NameRequest) (*SumPerDurationResponse, error)
}

func RegisterReporterServer(s *grpc.Server, srv ReporterServer) {
	s.RegisterService(&_Reporter_serviceDesc, srv)
}

func _Reporter_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reporter.Reporter/Discover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).Discover(ctx, req.(*DiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporter_Average_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).Average(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reporter.Reporter/Average",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).Average(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporter_AveragePerDuration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).AveragePerDuration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reporter.Reporter/AveragePerDuration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).AveragePerDuration(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporter_Counter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).Counter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reporter.Reporter/Counter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).Counter(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporter_CounterPerDuration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).CounterPerDuration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reporter.Reporter/CounterPerDuration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).CounterPerDuration(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporter_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reporter.Reporter/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).Sum(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporter_SumPerDuration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).SumPerDuration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reporter.Reporter/SumPerDuration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).SumPerDuration(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Reporter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "reporter.Reporter",
	HandlerType: (*ReporterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Discover",
			Handler:    _Reporter_Discover_Handler,
		},
		{
			MethodName: "Average",
			Handler:    _Reporter_Average_Handler,
		},
		{
			MethodName: "AveragePerDuration",
			Handler:    _Reporter_AveragePerDuration_Handler,
		},
		{
			MethodName: "Counter",
			Handler:    _Reporter_Counter_Handler,
		},
		{
			MethodName: "CounterPerDuration",
			Handler:    _Reporter_CounterPerDuration_Handler,
		},
		{
			MethodName: "Sum",
			Handler:    _Reporter_Sum_Handler,
		},
		{
			MethodName: "SumPerDuration",
			Handler:    _Reporter_SumPerDuration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reporter.proto",
}

func init() { proto.RegisterFile("reporter.proto", fileDescriptor_reporter_41a5be73b7b1da2b) }

var fileDescriptor_reporter_41a5be73b7b1da2b = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xae, 0x9b, 0x75, 0x74, 0xaf, 0xd3, 0x3a, 0x1e, 0xbf, 0x82, 0x2f, 0x0b, 0x16, 0x12, 0x3d,
	0x65, 0xd3, 0x10, 0x12, 0x1c, 0x38, 0xa0, 0xed, 0x86, 0x54, 0x21, 0x07, 0x6e, 0x5c, 0x3a, 0x30,
	0x55, 0xa5, 0x25, 0x0e, 0x8e, 0xdd, 0xbf, 0x86, 0xff, 0x94, 0x0b, 0x8a, 0xed, 0xa4, 0x49, 0x93,
	0xa0, 0xee, 0xe6, 0xf7, 0xf9, 0xcb, 0xe7, 0x2f, 0xef, 0x7d, 0x0f, 0xce, 0x94, 0xc8, 0xa5, 0xd2,
	0x42, 0xc5, 0xb9, 0x92, 0x5a, 0xe2, 0xb4, 0xaa, 0xe9, 0xc5, 0x5a, 0xca, 0xf5, 0xbd, 0xb8, 0xb4,
	0xf8, 0x9d, 0xf9, 0x75, 0xa9, 0x37, 0xa9, 0x28, 0xf4, 0x2a, 0xcd, 0x1d, 0x95, 0x3d, 0x86, 0xf9,
	0xed, 0xa6, 0xf8, 0x21, 0xb7, 0x42, 0x71, 0xf1, 0xdb, 0x88, 0x42, 0xb3, 0x3f, 0x63, 0x38, 0xdf,
	0x61, 0x45, 0x2e, 0xb3, 0x42, 0x20, 0x83, 0xd3, 0x4f, 0x5b, 0xa1, 0x56, 0x6b, 0xb1, 0x5c, 0xa5,
	0xa2, 0x08, 0x49, 0x14, 0x2c, 0x4e, 0x78, 0x0b, 0xc3, 0xf7, 0xf0, 0xc2, 0xd7, 0x5f, 0x84, 0xba,
	0x35, 0x6a, 0xa5, 0x37, 0x32, 0x73, 0xf4, 0xb1, 0xa5, 0x0f, 0x5d, 0x97, 0xea, 0x37, 0xd2, 0x64,
	0x5a, 0x28, 0x47, 0x0f, 0x9c, 0x7a, 0x13, 0x2b, 0xd5, 0x7d, 0xdd, 0x51, 0x3f, 0x72, 0xea, 0x03,
	0xd7, 0x48, 0x61, 0x9a, 0x98, 0xd4, 0x51, 0x27, 0x96, 0x5a, 0xd7, 0x78, 0x05, 0x4f, 0x12, 0x93,
	0x76, 0x14, 0x8f, 0x2d, 0xad, 0xef, 0x8a, 0xbd, 0x82, 0x59, 0x79, 0xf0, 0xdd, 0x42, 0x84, 0xa3,
	0xb2, 0x0c, 0x49, 0x44, 0x16, 0x27, 0xdc, 0x9e, 0xd9, 0x07, 0x98, 0xfb, 0x3f, 0xad, 0xfb, 0x17,
	0xc2, 0x23, 0x0f, 0x59, 0x26, 0xe1, 0x55, 0x89, 0xa7, 0x40, 0x96, 0xe1, 0x38, 0x22, 0x8b, 0x80,
	0x93, 0x25, 0xdb, 0x02, 0xed, 0x36, 0xe9, 0xa1, 0x2a, 0x78, 0x05, 0x93, 0x6f, 0x99, 0xde, 0xdc,
	0x87, 0x41, 0x44, 0x16, 0xb3, 0x6b, 0x1a, 0xbb, 0x18, 0xc4, 0x55, 0x0c, 0xe2, 0xaf, 0x55, 0x0c,
	0xb8, 0x23, 0xb2, 0x37, 0x30, 0xf7, 0xed, 0xab, 0x1f, 0x7b, 0x0a, 0x13, 0x0b, 0xd9, 0xa7, 0x02,
	0xee, 0x0a, 0xf6, 0x13, 0x68, 0xb7, 0xcf, 0xff, 0xff, 0x66, 0x67, 0x67, 0x7c, 0xa8, 0x9d, 0x0b,
	0x98, 0x25, 0x26, 0xad, 0x65, 0xcf, 0x21, 0x48, 0x4c, 0xea, 0xff, 0xb9, 0x3c, 0xb2, 0xef, 0xf0,
	0xbc, 0x3d, 0x9c, 0x61, 0xee, 0xc3, 0x9f, 0xbf, 0xfe, 0x1b, 0xc0, 0x94, 0xfb, 0x1d, 0xc2, 0x1b,
	0x98, 0x56, 0xeb, 0x80, 0x2f, 0xe3, 0x7a, 0xd5, 0xf6, 0xd6, 0x86, 0xd2, 0xbe, 0x2b, 0xe7, 0x89,
	0x8d, 0xf0, 0x63, 0x3d, 0x39, 0x7c, 0xb6, 0x23, 0x36, 0x82, 0x44, 0x1b, 0xd2, 0x7b, 0xe1, 0x61,
	0x23, 0x4c, 0x00, 0xbb, 0xb1, 0x18, 0x52, 0x7a, 0xdd, 0x51, 0xea, 0xe9, 0x93, 0xf3, 0xe4, 0x47,
	0x79, 0x80, 0xa7, 0xbd, 0x74, 0x38, 0x4f, 0xdd, 0x24, 0x1c, 0xe0, 0x69, 0x38, 0x3e, 0x6c, 0x84,
	0xef, 0xec, 0xf4, 0x86, 0x54, 0x1a, 0x70, 0x23, 0x1e, 0x6c, 0x84, 0x9f, 0xe1, 0xac, 0x1d, 0x87,
	0x21, 0x85, 0xa8, 0xa5, 0xd0, 0xeb, 0xe1, 0xee, 0xd8, 0x06, 0xe3, 0xed, 0xbf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x5e, 0x93, 0xbf, 0xbd, 0x57, 0x05, 0x00, 0x00,
}
