#!/bin/sh

# install-precommit-hook adds pre-commit.pl as the precommit hook to
# ~/git/hooks/.

function error() {
    echo "$@" 1>&2
    exit 1
}

test -d .git ||
    error "You must be in the top level directory to do this (no .git/ found here)"

diff tools/pre-commit.pl .git/hooks/pre-commit >/dev/null 2>&1
if [ $? -ne 0 ] ; then
    cp tools/pre-commit.pl .git/hooks/pre-commit ||
	error "cp failed"
    chmod +x .git/hooks/pre-commit ||
	error "chmod failed"
fi
