#!/bin/sh

# install-prepush-hook adds pre-push.pl as the prepush hook to
# ~/git/hooks/.

function error() {
    echo "$@" 1>&2
    exit 1
}

test -d .git ||
    error "You must be in the top level directory to do this (no .git/ found here)"

diff tools/pre-push.pl .git/hooks/pre-push >/dev/null 2>&1
if [ $? -ne 0 ] ; then
    cp tools/pre-push.pl .git/hooks/pre-push ||
	error "cp failed"
    chmod +x .git/hooks/pre-push ||
	error "chmod failed"
fi
