// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Discovery of all the names
type AllNamesResponse struct {
	AverageNames            []string `protobuf:"bytes,1,rep,name=AverageNames,proto3" json:"AverageNames,omitempty"`
	AveragePerDurationNames []string `protobuf:"bytes,2,rep,name=AveragePerDurationNames,proto3" json:"AveragePerDurationNames,omitempty"`
	CountNames              []string `protobuf:"bytes,3,rep,name=CountNames,proto3" json:"CountNames,omitempty"`
	CountPerDurationNames   []string `protobuf:"bytes,4,rep,name=CountPerDurationNames,proto3" json:"CountPerDurationNames,omitempty"`
	SumNames                []string `protobuf:"bytes,5,rep,name=SumNames,proto3" json:"SumNames,omitempty"`
	SumPerDurationNames     []string `protobuf:"bytes,6,rep,name=SumPerDurationNames,proto3" json:"SumPerDurationNames,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *AllNamesResponse) Reset()         { *m = AllNamesResponse{} }
func (m *AllNamesResponse) String() string { return proto.CompactTextString(m) }
func (*AllNamesResponse) ProtoMessage()    {}
func (*AllNamesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_93225da898caf379, []int{0}
}
func (m *AllNamesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllNamesResponse.Unmarshal(m, b)
}
func (m *AllNamesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllNamesResponse.Marshal(b, m, deterministic)
}
func (dst *AllNamesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllNamesResponse.Merge(dst, src)
}
func (m *AllNamesResponse) XXX_Size() int {
	return xxx_messageInfo_AllNamesResponse.Size(m)
}
func (m *AllNamesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllNamesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllNamesResponse proto.InternalMessageInfo

func (m *AllNamesResponse) GetAverageNames() []string {
	if m != nil {
		return m.AverageNames
	}
	return nil
}

func (m *AllNamesResponse) GetAveragePerDurationNames() []string {
	if m != nil {
		return m.AveragePerDurationNames
	}
	return nil
}

func (m *AllNamesResponse) GetCountNames() []string {
	if m != nil {
		return m.CountNames
	}
	return nil
}

func (m *AllNamesResponse) GetCountPerDurationNames() []string {
	if m != nil {
		return m.CountPerDurationNames
	}
	return nil
}

func (m *AllNamesResponse) GetSumNames() []string {
	if m != nil {
		return m.SumNames
	}
	return nil
}

func (m *AllNamesResponse) GetSumPerDurationNames() []string {
	if m != nil {
		return m.SumPerDurationNames
	}
	return nil
}

// Requesting a metric by name
type NameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameRequest) Reset()         { *m = NameRequest{} }
func (m *NameRequest) String() string { return proto.CompactTextString(m) }
func (*NameRequest) ProtoMessage()    {}
func (*NameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_93225da898caf379, []int{1}
}
func (m *NameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameRequest.Unmarshal(m, b)
}
func (m *NameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameRequest.Marshal(b, m, deterministic)
}
func (dst *NameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameRequest.Merge(dst, src)
}
func (m *NameRequest) XXX_Size() int {
	return xxx_messageInfo_NameRequest.Size(m)
}
func (m *NameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NameRequest proto.InternalMessageInfo

func (m *NameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Responding to an average
type AverageResponse struct {
	Average              float64  `protobuf:"fixed64,1,opt,name=Average,proto3" json:"Average,omitempty"`
	N                    int64    `protobuf:"varint,2,opt,name=N,proto3" json:"N,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AverageResponse) Reset()         { *m = AverageResponse{} }
func (m *AverageResponse) String() string { return proto.CompactTextString(m) }
func (*AverageResponse) ProtoMessage()    {}
func (*AverageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_93225da898caf379, []int{2}
}
func (m *AverageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AverageResponse.Unmarshal(m, b)
}
func (m *AverageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AverageResponse.Marshal(b, m, deterministic)
}
func (dst *AverageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AverageResponse.Merge(dst, src)
}
func (m *AverageResponse) XXX_Size() int {
	return xxx_messageInfo_AverageResponse.Size(m)
}
func (m *AverageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AverageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AverageResponse proto.InternalMessageInfo

func (m *AverageResponse) GetAverage() float64 {
	if m != nil {
		return m.Average
	}
	return 0
}

func (m *AverageResponse) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

// Responding to an average per duration
type AveragePerDurationResponse struct {
	Average              float64              `protobuf:"fixed64,1,opt,name=Average,proto3" json:"Average,omitempty"`
	N                    int64                `protobuf:"varint,2,opt,name=N,proto3" json:"N,omitempty"`
	Until                *timestamp.Timestamp `protobuf:"bytes,3,opt,name=Until,proto3" json:"Until,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AveragePerDurationResponse) Reset()         { *m = AveragePerDurationResponse{} }
func (m *AveragePerDurationResponse) String() string { return proto.CompactTextString(m) }
func (*AveragePerDurationResponse) ProtoMessage()    {}
func (*AveragePerDurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_93225da898caf379, []int{3}
}
func (m *AveragePerDurationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AveragePerDurationResponse.Unmarshal(m, b)
}
func (m *AveragePerDurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AveragePerDurationResponse.Marshal(b, m, deterministic)
}
func (dst *AveragePerDurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AveragePerDurationResponse.Merge(dst, src)
}
func (m *AveragePerDurationResponse) XXX_Size() int {
	return xxx_messageInfo_AveragePerDurationResponse.Size(m)
}
func (m *AveragePerDurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AveragePerDurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AveragePerDurationResponse proto.InternalMessageInfo

func (m *AveragePerDurationResponse) GetAverage() float64 {
	if m != nil {
		return m.Average
	}
	return 0
}

func (m *AveragePerDurationResponse) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *AveragePerDurationResponse) GetUntil() *timestamp.Timestamp {
	if m != nil {
		return m.Until
	}
	return nil
}

type CountResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountResponse) Reset()         { *m = CountResponse{} }
func (m *CountResponse) String() string { return proto.CompactTextString(m) }
func (*CountResponse) ProtoMessage()    {}
func (*CountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_93225da898caf379, []int{4}
}
func (m *CountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountResponse.Unmarshal(m, b)
}
func (m *CountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountResponse.Marshal(b, m, deterministic)
}
func (dst *CountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountResponse.Merge(dst, src)
}
func (m *CountResponse) XXX_Size() int {
	return xxx_messageInfo_CountResponse.Size(m)
}
func (m *CountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountResponse proto.InternalMessageInfo

func (m *CountResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CountPerDurationResponse struct {
	Count                int64                `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	Until                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=Until,proto3" json:"Until,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CountPerDurationResponse) Reset()         { *m = CountPerDurationResponse{} }
func (m *CountPerDurationResponse) String() string { return proto.CompactTextString(m) }
func (*CountPerDurationResponse) ProtoMessage()    {}
func (*CountPerDurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_93225da898caf379, []int{5}
}
func (m *CountPerDurationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountPerDurationResponse.Unmarshal(m, b)
}
func (m *CountPerDurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountPerDurationResponse.Marshal(b, m, deterministic)
}
func (dst *CountPerDurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountPerDurationResponse.Merge(dst, src)
}
func (m *CountPerDurationResponse) XXX_Size() int {
	return xxx_messageInfo_CountPerDurationResponse.Size(m)
}
func (m *CountPerDurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountPerDurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountPerDurationResponse proto.InternalMessageInfo

func (m *CountPerDurationResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *CountPerDurationResponse) GetUntil() *timestamp.Timestamp {
	if m != nil {
		return m.Until
	}
	return nil
}

type SumResponse struct {
	Sum                  float64  `protobuf:"fixed64,1,opt,name=Sum,proto3" json:"Sum,omitempty"`
	N                    int64    `protobuf:"varint,2,opt,name=N,proto3" json:"N,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_93225da898caf379, []int{6}
}
func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (dst *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(dst, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetSum() float64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *SumResponse) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

type SumPerDurationResponse struct {
	Sum                  float64              `protobuf:"fixed64,1,opt,name=Sum,proto3" json:"Sum,omitempty"`
	N                    int64                `protobuf:"varint,2,opt,name=N,proto3" json:"N,omitempty"`
	Until                *timestamp.Timestamp `protobuf:"bytes,3,opt,name=Until,proto3" json:"Until,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SumPerDurationResponse) Reset()         { *m = SumPerDurationResponse{} }
func (m *SumPerDurationResponse) String() string { return proto.CompactTextString(m) }
func (*SumPerDurationResponse) ProtoMessage()    {}
func (*SumPerDurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_93225da898caf379, []int{7}
}
func (m *SumPerDurationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumPerDurationResponse.Unmarshal(m, b)
}
func (m *SumPerDurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumPerDurationResponse.Marshal(b, m, deterministic)
}
func (dst *SumPerDurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumPerDurationResponse.Merge(dst, src)
}
func (m *SumPerDurationResponse) XXX_Size() int {
	return xxx_messageInfo_SumPerDurationResponse.Size(m)
}
func (m *SumPerDurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumPerDurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumPerDurationResponse proto.InternalMessageInfo

func (m *SumPerDurationResponse) GetSum() float64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *SumPerDurationResponse) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *SumPerDurationResponse) GetUntil() *timestamp.Timestamp {
	if m != nil {
		return m.Until
	}
	return nil
}

type NamedAverage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Value                float64  `protobuf:"fixed64,2,opt,name=Value,proto3" json:"Value,omitempty"`
	N                    int64    `protobuf:"varint,3,opt,name=N,proto3" json:"N,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamedAverage) Reset()         { *m = NamedAverage{} }
func (m *NamedAverage) String() string { return proto.CompactTextString(m) }
func (*NamedAverage) ProtoMessage()    {}
func (*NamedAverage) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_93225da898caf379, []int{8}
}
func (m *NamedAverage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedAverage.Unmarshal(m, b)
}
func (m *NamedAverage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedAverage.Marshal(b, m, deterministic)
}
func (dst *NamedAverage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedAverage.Merge(dst, src)
}
func (m *NamedAverage) XXX_Size() int {
	return xxx_messageInfo_NamedAverage.Size(m)
}
func (m *NamedAverage) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedAverage.DiscardUnknown(m)
}

var xxx_messageInfo_NamedAverage proto.InternalMessageInfo

func (m *NamedAverage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NamedAverage) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *NamedAverage) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

type NamedAveragePerDuration struct {
	Name                 string               `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Value                float64              `protobuf:"fixed64,2,opt,name=Value,proto3" json:"Value,omitempty"`
	N                    int64                `protobuf:"varint,3,opt,name=N,proto3" json:"N,omitempty"`
	Until                *timestamp.Timestamp `protobuf:"bytes,4,opt,name=Until,proto3" json:"Until,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NamedAveragePerDuration) Reset()         { *m = NamedAveragePerDuration{} }
func (m *NamedAveragePerDuration) String() string { return proto.CompactTextString(m) }
func (*NamedAveragePerDuration) ProtoMessage()    {}
func (*NamedAveragePerDuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_93225da898caf379, []int{9}
}
func (m *NamedAveragePerDuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedAveragePerDuration.Unmarshal(m, b)
}
func (m *NamedAveragePerDuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedAveragePerDuration.Marshal(b, m, deterministic)
}
func (dst *NamedAveragePerDuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedAveragePerDuration.Merge(dst, src)
}
func (m *NamedAveragePerDuration) XXX_Size() int {
	return xxx_messageInfo_NamedAveragePerDuration.Size(m)
}
func (m *NamedAveragePerDuration) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedAveragePerDuration.DiscardUnknown(m)
}

var xxx_messageInfo_NamedAveragePerDuration proto.InternalMessageInfo

func (m *NamedAveragePerDuration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NamedAveragePerDuration) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *NamedAveragePerDuration) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *NamedAveragePerDuration) GetUntil() *timestamp.Timestamp {
	if m != nil {
		return m.Until
	}
	return nil
}

type NamedCount struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Value                int64    `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamedCount) Reset()         { *m = NamedCount{} }
func (m *NamedCount) String() string { return proto.CompactTextString(m) }
func (*NamedCount) ProtoMessage()    {}
func (*NamedCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_93225da898caf379, []int{10}
}
func (m *NamedCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedCount.Unmarshal(m, b)
}
func (m *NamedCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedCount.Marshal(b, m, deterministic)
}
func (dst *NamedCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedCount.Merge(dst, src)
}
func (m *NamedCount) XXX_Size() int {
	return xxx_messageInfo_NamedCount.Size(m)
}
func (m *NamedCount) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedCount.DiscardUnknown(m)
}

var xxx_messageInfo_NamedCount proto.InternalMessageInfo

func (m *NamedCount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NamedCount) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type NamedCountPerDuration struct {
	Name                 string               `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Value                int64                `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Until                *timestamp.Timestamp `protobuf:"bytes,3,opt,name=Until,proto3" json:"Until,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NamedCountPerDuration) Reset()         { *m = NamedCountPerDuration{} }
func (m *NamedCountPerDuration) String() string { return proto.CompactTextString(m) }
func (*NamedCountPerDuration) ProtoMessage()    {}
func (*NamedCountPerDuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_93225da898caf379, []int{11}
}
func (m *NamedCountPerDuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedCountPerDuration.Unmarshal(m, b)
}
func (m *NamedCountPerDuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedCountPerDuration.Marshal(b, m, deterministic)
}
func (dst *NamedCountPerDuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedCountPerDuration.Merge(dst, src)
}
func (m *NamedCountPerDuration) XXX_Size() int {
	return xxx_messageInfo_NamedCountPerDuration.Size(m)
}
func (m *NamedCountPerDuration) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedCountPerDuration.DiscardUnknown(m)
}

var xxx_messageInfo_NamedCountPerDuration proto.InternalMessageInfo

func (m *NamedCountPerDuration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NamedCountPerDuration) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *NamedCountPerDuration) GetUntil() *timestamp.Timestamp {
	if m != nil {
		return m.Until
	}
	return nil
}

type NamedSum struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Value                float64  `protobuf:"fixed64,2,opt,name=Value,proto3" json:"Value,omitempty"`
	N                    int64    `protobuf:"varint,3,opt,name=N,proto3" json:"N,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NamedSum) Reset()         { *m = NamedSum{} }
func (m *NamedSum) String() string { return proto.CompactTextString(m) }
func (*NamedSum) ProtoMessage()    {}
func (*NamedSum) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_93225da898caf379, []int{12}
}
func (m *NamedSum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedSum.Unmarshal(m, b)
}
func (m *NamedSum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedSum.Marshal(b, m, deterministic)
}
func (dst *NamedSum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedSum.Merge(dst, src)
}
func (m *NamedSum) XXX_Size() int {
	return xxx_messageInfo_NamedSum.Size(m)
}
func (m *NamedSum) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedSum.DiscardUnknown(m)
}

var xxx_messageInfo_NamedSum proto.InternalMessageInfo

func (m *NamedSum) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NamedSum) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *NamedSum) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

type NamedSumPerDuration struct {
	Name                 string               `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Value                float64              `protobuf:"fixed64,2,opt,name=Value,proto3" json:"Value,omitempty"`
	N                    int64                `protobuf:"varint,3,opt,name=N,proto3" json:"N,omitempty"`
	Until                *timestamp.Timestamp `protobuf:"bytes,4,opt,name=Until,proto3" json:"Until,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NamedSumPerDuration) Reset()         { *m = NamedSumPerDuration{} }
func (m *NamedSumPerDuration) String() string { return proto.CompactTextString(m) }
func (*NamedSumPerDuration) ProtoMessage()    {}
func (*NamedSumPerDuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_93225da898caf379, []int{13}
}
func (m *NamedSumPerDuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedSumPerDuration.Unmarshal(m, b)
}
func (m *NamedSumPerDuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedSumPerDuration.Marshal(b, m, deterministic)
}
func (dst *NamedSumPerDuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedSumPerDuration.Merge(dst, src)
}
func (m *NamedSumPerDuration) XXX_Size() int {
	return xxx_messageInfo_NamedSumPerDuration.Size(m)
}
func (m *NamedSumPerDuration) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedSumPerDuration.DiscardUnknown(m)
}

var xxx_messageInfo_NamedSumPerDuration proto.InternalMessageInfo

func (m *NamedSumPerDuration) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NamedSumPerDuration) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *NamedSumPerDuration) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *NamedSumPerDuration) GetUntil() *timestamp.Timestamp {
	if m != nil {
		return m.Until
	}
	return nil
}

type FullDumpResponse struct {
	NamedAverages            []*NamedAverage            `protobuf:"bytes,1,rep,name=NamedAverages,proto3" json:"NamedAverages,omitempty"`
	NamedAveragesPerDuration []*NamedAveragePerDuration `protobuf:"bytes,2,rep,name=NamedAveragesPerDuration,proto3" json:"NamedAveragesPerDuration,omitempty"`
	NamedCounts              []*NamedCount              `protobuf:"bytes,3,rep,name=NamedCounts,proto3" json:"NamedCounts,omitempty"`
	NamedCountsPerDuration   []*NamedCountPerDuration   `protobuf:"bytes,4,rep,name=NamedCountsPerDuration,proto3" json:"NamedCountsPerDuration,omitempty"`
	NamedSums                []*NamedSum                `protobuf:"bytes,5,rep,name=NamedSums,proto3" json:"NamedSums,omitempty"`
	NamedSumsPerDuration     []*NamedSumPerDuration     `protobuf:"bytes,6,rep,name=NamedSumsPerDuration,proto3" json:"NamedSumsPerDuration,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                   `json:"-"`
	XXX_unrecognized         []byte                     `json:"-"`
	XXX_sizecache            int32                      `json:"-"`
}

func (m *FullDumpResponse) Reset()         { *m = FullDumpResponse{} }
func (m *FullDumpResponse) String() string { return proto.CompactTextString(m) }
func (*FullDumpResponse) ProtoMessage()    {}
func (*FullDumpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_93225da898caf379, []int{14}
}
func (m *FullDumpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FullDumpResponse.Unmarshal(m, b)
}
func (m *FullDumpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FullDumpResponse.Marshal(b, m, deterministic)
}
func (dst *FullDumpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FullDumpResponse.Merge(dst, src)
}
func (m *FullDumpResponse) XXX_Size() int {
	return xxx_messageInfo_FullDumpResponse.Size(m)
}
func (m *FullDumpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FullDumpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FullDumpResponse proto.InternalMessageInfo

func (m *FullDumpResponse) GetNamedAverages() []*NamedAverage {
	if m != nil {
		return m.NamedAverages
	}
	return nil
}

func (m *FullDumpResponse) GetNamedAveragesPerDuration() []*NamedAveragePerDuration {
	if m != nil {
		return m.NamedAveragesPerDuration
	}
	return nil
}

func (m *FullDumpResponse) GetNamedCounts() []*NamedCount {
	if m != nil {
		return m.NamedCounts
	}
	return nil
}

func (m *FullDumpResponse) GetNamedCountsPerDuration() []*NamedCountPerDuration {
	if m != nil {
		return m.NamedCountsPerDuration
	}
	return nil
}

func (m *FullDumpResponse) GetNamedSums() []*NamedSum {
	if m != nil {
		return m.NamedSums
	}
	return nil
}

func (m *FullDumpResponse) GetNamedSumsPerDuration() []*NamedSumPerDuration {
	if m != nil {
		return m.NamedSumsPerDuration
	}
	return nil
}

func init() {
	proto.RegisterType((*AllNamesResponse)(nil), "api.AllNamesResponse")
	proto.RegisterType((*NameRequest)(nil), "api.NameRequest")
	proto.RegisterType((*AverageResponse)(nil), "api.AverageResponse")
	proto.RegisterType((*AveragePerDurationResponse)(nil), "api.AveragePerDurationResponse")
	proto.RegisterType((*CountResponse)(nil), "api.CountResponse")
	proto.RegisterType((*CountPerDurationResponse)(nil), "api.CountPerDurationResponse")
	proto.RegisterType((*SumResponse)(nil), "api.SumResponse")
	proto.RegisterType((*SumPerDurationResponse)(nil), "api.SumPerDurationResponse")
	proto.RegisterType((*NamedAverage)(nil), "api.NamedAverage")
	proto.RegisterType((*NamedAveragePerDuration)(nil), "api.NamedAveragePerDuration")
	proto.RegisterType((*NamedCount)(nil), "api.NamedCount")
	proto.RegisterType((*NamedCountPerDuration)(nil), "api.NamedCountPerDuration")
	proto.RegisterType((*NamedSum)(nil), "api.NamedSum")
	proto.RegisterType((*NamedSumPerDuration)(nil), "api.NamedSumPerDuration")
	proto.RegisterType((*FullDumpResponse)(nil), "api.FullDumpResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReporterClient is the client API for Reporter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReporterClient interface {
	AllNames(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AllNamesResponse, error)
	FullDump(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FullDumpResponse, error)
	Average(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*AverageResponse, error)
	AveragePerDuration(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*AveragePerDurationResponse, error)
	Count(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*CountResponse, error)
	CountPerDuration(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*CountPerDurationResponse, error)
	Sum(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*SumResponse, error)
	SumPerDuration(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*SumPerDurationResponse, error)
}

type reporterClient struct {
	cc *grpc.ClientConn
}

func NewReporterClient(cc *grpc.ClientConn) ReporterClient {
	return &reporterClient{cc}
}

func (c *reporterClient) AllNames(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AllNamesResponse, error) {
	out := new(AllNamesResponse)
	err := c.cc.Invoke(ctx, "/api.Reporter/AllNames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterClient) FullDump(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FullDumpResponse, error) {
	out := new(FullDumpResponse)
	err := c.cc.Invoke(ctx, "/api.Reporter/FullDump", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterClient) Average(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*AverageResponse, error) {
	out := new(AverageResponse)
	err := c.cc.Invoke(ctx, "/api.Reporter/Average", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterClient) AveragePerDuration(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*AveragePerDurationResponse, error) {
	out := new(AveragePerDurationResponse)
	err := c.cc.Invoke(ctx, "/api.Reporter/AveragePerDuration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterClient) Count(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, "/api.Reporter/Count", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterClient) CountPerDuration(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*CountPerDurationResponse, error) {
	out := new(CountPerDurationResponse)
	err := c.cc.Invoke(ctx, "/api.Reporter/CountPerDuration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterClient) Sum(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/api.Reporter/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterClient) SumPerDuration(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*SumPerDurationResponse, error) {
	out := new(SumPerDurationResponse)
	err := c.cc.Invoke(ctx, "/api.Reporter/SumPerDuration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReporterServer is the server API for Reporter service.
type ReporterServer interface {
	AllNames(context.Context, *empty.Empty) (*AllNamesResponse, error)
	FullDump(context.Context, *empty.Empty) (*FullDumpResponse, error)
	Average(context.Context, *NameRequest) (*AverageResponse, error)
	AveragePerDuration(context.Context, *NameRequest) (*AveragePerDurationResponse, error)
	Count(context.Context, *NameRequest) (*CountResponse, error)
	CountPerDuration(context.Context, *NameRequest) (*CountPerDurationResponse, error)
	Sum(context.Context, *NameRequest) (*SumResponse, error)
	SumPerDuration(context.Context, *NameRequest) (*SumPerDurationResponse, error)
}

func RegisterReporterServer(s *grpc.Server, srv ReporterServer) {
	s.RegisterService(&_Reporter_serviceDesc, srv)
}

func _Reporter_AllNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).AllNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Reporter/AllNames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).AllNames(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporter_FullDump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).FullDump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Reporter/FullDump",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).FullDump(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporter_Average_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).Average(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Reporter/Average",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).Average(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporter_AveragePerDuration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).AveragePerDuration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Reporter/AveragePerDuration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).AveragePerDuration(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporter_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Reporter/Count",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).Count(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporter_CountPerDuration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).CountPerDuration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Reporter/CountPerDuration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).CountPerDuration(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporter_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Reporter/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).Sum(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporter_SumPerDuration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).SumPerDuration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Reporter/SumPerDuration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).SumPerDuration(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Reporter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Reporter",
	HandlerType: (*ReporterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllNames",
			Handler:    _Reporter_AllNames_Handler,
		},
		{
			MethodName: "FullDump",
			Handler:    _Reporter_FullDump_Handler,
		},
		{
			MethodName: "Average",
			Handler:    _Reporter_Average_Handler,
		},
		{
			MethodName: "AveragePerDuration",
			Handler:    _Reporter_AveragePerDuration_Handler,
		},
		{
			MethodName: "Count",
			Handler:    _Reporter_Count_Handler,
		},
		{
			MethodName: "CountPerDuration",
			Handler:    _Reporter_CountPerDuration_Handler,
		},
		{
			MethodName: "Sum",
			Handler:    _Reporter_Sum_Handler,
		},
		{
			MethodName: "SumPerDuration",
			Handler:    _Reporter_SumPerDuration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_93225da898caf379) }

var fileDescriptor_api_93225da898caf379 = []byte{
	// 682 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xdb, 0x6e, 0xd3, 0x40,
	0x10, 0xb5, 0xe3, 0xb4, 0x24, 0xe3, 0x96, 0x86, 0xe9, 0xcd, 0x72, 0x81, 0x86, 0x95, 0x90, 0x22,
	0x55, 0xa4, 0xc5, 0x45, 0x5c, 0xc4, 0x53, 0xa1, 0xad, 0x84, 0x84, 0x22, 0xb4, 0x01, 0xc4, 0xab,
	0x23, 0x96, 0x28, 0xc8, 0x8e, 0x8d, 0x2f, 0x95, 0x78, 0xe2, 0x81, 0x5f, 0xe0, 0x1f, 0xf8, 0x39,
	0x3e, 0x02, 0x79, 0xd7, 0x97, 0xf5, 0x25, 0x34, 0xcd, 0x0b, 0x6f, 0x9e, 0xd9, 0x73, 0x66, 0x66,
	0x67, 0xd6, 0x67, 0xa0, 0x6b, 0xfb, 0xb3, 0xa1, 0x1f, 0x78, 0x91, 0x87, 0x9a, 0xed, 0xcf, 0xcc,
	0x83, 0xa9, 0xe7, 0x4d, 0x1d, 0x76, 0xcc, 0x5d, 0x93, 0xf8, 0xcb, 0x31, 0x73, 0xfd, 0xe8, 0xbb,
	0x40, 0x98, 0x87, 0xd5, 0xc3, 0x68, 0xe6, 0xb2, 0x30, 0xb2, 0x5d, 0x5f, 0x00, 0xc8, 0xaf, 0x16,
	0xf4, 0xce, 0x1c, 0x67, 0x64, 0xbb, 0x2c, 0xa4, 0x2c, 0xf4, 0xbd, 0x79, 0xc8, 0x90, 0xc0, 0xc6,
	0xd9, 0x15, 0x0b, 0xec, 0x29, 0xe3, 0x7e, 0x43, 0xed, 0x6b, 0x83, 0x2e, 0x2d, 0xf9, 0xf0, 0x39,
	0xec, 0xa7, 0xf6, 0x3b, 0x16, 0x9c, 0xc7, 0x81, 0x1d, 0xcd, 0xbc, 0xb9, 0x80, 0xb7, 0x38, 0x7c,
	0xd1, 0x31, 0xde, 0x07, 0x78, 0xed, 0xc5, 0xf3, 0x48, 0x80, 0x35, 0x0e, 0x96, 0x3c, 0xf8, 0x04,
	0x76, 0xb9, 0x55, 0x8b, 0xdb, 0xe6, 0xd0, 0xe6, 0x43, 0x34, 0xa1, 0x33, 0x8e, 0x5d, 0x01, 0x5c,
	0xe3, 0xc0, 0xdc, 0xc6, 0x13, 0xd8, 0x1e, 0xc7, 0x6e, 0x2d, 0xde, 0x3a, 0x87, 0x35, 0x1d, 0x91,
	0x07, 0xa0, 0x27, 0x1f, 0x94, 0x7d, 0x8b, 0x59, 0x18, 0x21, 0x42, 0x3b, 0x31, 0x0d, 0xb5, 0xaf,
	0x0e, 0xba, 0x94, 0x7f, 0x93, 0x17, 0xb0, 0x95, 0xde, 0x30, 0xef, 0x9b, 0x01, 0xb7, 0x52, 0x17,
	0x47, 0xaa, 0x34, 0x33, 0x71, 0x03, 0xd4, 0x91, 0xd1, 0xea, 0xab, 0x03, 0x8d, 0xaa, 0x23, 0x72,
	0x05, 0x66, 0xbd, 0x39, 0x37, 0x8d, 0x82, 0x27, 0xb0, 0xf6, 0x61, 0x1e, 0xcd, 0x1c, 0x43, 0xeb,
	0xab, 0x03, 0xdd, 0x32, 0x87, 0x62, 0xd6, 0xc3, 0x6c, 0xd6, 0xc3, 0xf7, 0xd9, 0xac, 0xa9, 0x00,
	0x92, 0x87, 0xb0, 0xc9, 0x9b, 0x97, 0xa7, 0xda, 0x81, 0x35, 0xee, 0xe0, 0x89, 0x34, 0x2a, 0x0c,
	0x32, 0x01, 0xa3, 0xda, 0xe3, 0x7f, 0x33, 0x8a, 0x52, 0x5a, 0xcb, 0x96, 0xf2, 0x08, 0xf4, 0x71,
	0xec, 0xe6, 0x61, 0x7b, 0xa0, 0x8d, 0x63, 0x37, 0xbd, 0x6f, 0xf2, 0x59, 0xe9, 0xd8, 0x57, 0xd8,
	0x2b, 0x8f, 0x69, 0x59, 0xe6, 0x0a, 0x5d, 0xba, 0x84, 0x8d, 0x64, 0xc0, 0x9f, 0xb3, 0xae, 0x37,
	0x0c, 0x3f, 0x69, 0xc3, 0x47, 0xdb, 0x89, 0x19, 0xcf, 0xa3, 0x52, 0x61, 0x88, 0xcc, 0x5a, 0x56,
	0xf3, 0x4f, 0x15, 0xf6, 0xe5, 0x40, 0x52, 0xf5, 0xab, 0xc6, 0x2c, 0x6e, 0xd3, 0x5e, 0xf6, 0x36,
	0x4f, 0x01, 0x78, 0x11, 0x62, 0x50, 0xd7, 0xe6, 0xd5, 0xd2, 0xbc, 0x24, 0x84, 0xdd, 0x82, 0x77,
	0xa3, 0xd2, 0xb3, 0x10, 0x2b, 0xb4, 0xfe, 0x15, 0x74, 0x78, 0xd2, 0x64, 0x8c, 0xab, 0xb6, 0xfd,
	0x07, 0x6c, 0x67, 0x31, 0xfe, 0x4f, 0xc7, 0x7f, 0x6b, 0xd0, 0xbb, 0x8c, 0x1d, 0xe7, 0x3c, 0x76,
	0xfd, 0xfc, 0x99, 0x3e, 0x83, 0x4d, 0xf9, 0x2d, 0x08, 0x4d, 0xd5, 0xad, 0x3b, 0xc3, 0x44, 0xcd,
	0xe5, 0x13, 0x5a, 0xc6, 0xe1, 0x27, 0x30, 0x4a, 0x0e, 0xe9, 0x4e, 0x5c, 0x68, 0x75, 0xeb, 0x6e,
	0x2d, 0x86, 0xfc, 0x9f, 0x2c, 0x64, 0xe3, 0x63, 0xa1, 0x71, 0x62, 0xc2, 0x42, 0x88, 0x75, 0x6b,
	0xab, 0x08, 0x26, 0xa4, 0x42, 0xc6, 0x20, 0x85, 0x3d, 0xc9, 0x94, 0x4b, 0x69, 0x73, 0xb6, 0x59,
	0x61, 0xcb, 0x85, 0x2c, 0x60, 0xe2, 0x11, 0x74, 0xb3, 0x79, 0x09, 0xe5, 0xd6, 0xad, 0xcd, 0x22,
	0x4c, 0x22, 0x12, 0xc5, 0x39, 0xbe, 0x85, 0x9d, 0xdc, 0x90, 0xd3, 0xaf, 0x73, 0x9e, 0x51, 0xe2,
	0xc9, 0xc9, 0x1b, 0x59, 0xd6, 0x1f, 0x0d, 0x3a, 0x94, 0xf9, 0x5e, 0x10, 0xb1, 0x00, 0x5f, 0x42,
	0x27, 0x5b, 0x84, 0xb8, 0x57, 0x9b, 0xf2, 0x45, 0xb2, 0x54, 0xcd, 0x5d, 0x9e, 0xa0, 0xba, 0x2f,
	0x89, 0x92, 0x90, 0xb3, 0x91, 0x5f, 0x43, 0xae, 0xbe, 0x0c, 0xa2, 0xe0, 0x69, 0x2e, 0xf8, 0xd8,
	0xcb, 0x6f, 0x90, 0xae, 0x1e, 0x73, 0x47, 0xa4, 0x2c, 0x6f, 0x1a, 0xa2, 0xe0, 0x1b, 0xc0, 0x06,
	0x5d, 0xa9, 0xf3, 0x0f, 0x65, 0x7e, 0x83, 0x80, 0x12, 0x05, 0x8f, 0x53, 0x4d, 0x6f, 0x60, 0x23,
	0xf7, 0x94, 0x96, 0x06, 0x51, 0xf0, 0x02, 0x7a, 0x35, 0x59, 0xa8, 0x73, 0xef, 0x15, 0xdc, 0xe6,
	0xbc, 0x47, 0x5c, 0xba, 0x1b, 0x98, 0xc2, 0x23, 0xed, 0x07, 0xa2, 0xe0, 0x19, 0xdc, 0xae, 0xfc,
	0xd1, 0x75, 0xde, 0x41, 0xc6, 0x6b, 0xcc, 0x37, 0x59, 0xe7, 0x03, 0x39, 0xfd, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0xa3, 0x89, 0xad, 0x44, 0x42, 0x09, 0x00, 0x00,
}
