// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Discovery of all the names
type AllNamesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllNamesRequest) Reset()         { *m = AllNamesRequest{} }
func (m *AllNamesRequest) String() string { return proto.CompactTextString(m) }
func (*AllNamesRequest) ProtoMessage()    {}
func (*AllNamesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d05eb8469fe335f1, []int{0}
}
func (m *AllNamesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllNamesRequest.Unmarshal(m, b)
}
func (m *AllNamesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllNamesRequest.Marshal(b, m, deterministic)
}
func (dst *AllNamesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllNamesRequest.Merge(dst, src)
}
func (m *AllNamesRequest) XXX_Size() int {
	return xxx_messageInfo_AllNamesRequest.Size(m)
}
func (m *AllNamesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllNamesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllNamesRequest proto.InternalMessageInfo

type AllNamesResponse struct {
	AverageNames            []string `protobuf:"bytes,1,rep,name=AverageNames,proto3" json:"AverageNames,omitempty"`
	AveragePerDurationNames []string `protobuf:"bytes,2,rep,name=AveragePerDurationNames,proto3" json:"AveragePerDurationNames,omitempty"`
	CountNames              []string `protobuf:"bytes,3,rep,name=CountNames,proto3" json:"CountNames,omitempty"`
	CountPerDurationNames   []string `protobuf:"bytes,4,rep,name=CountPerDurationNames,proto3" json:"CountPerDurationNames,omitempty"`
	SumNames                []string `protobuf:"bytes,5,rep,name=SumNames,proto3" json:"SumNames,omitempty"`
	SumPerDurationNames     []string `protobuf:"bytes,6,rep,name=SumPerDurationNames,proto3" json:"SumPerDurationNames,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *AllNamesResponse) Reset()         { *m = AllNamesResponse{} }
func (m *AllNamesResponse) String() string { return proto.CompactTextString(m) }
func (*AllNamesResponse) ProtoMessage()    {}
func (*AllNamesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d05eb8469fe335f1, []int{1}
}
func (m *AllNamesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllNamesResponse.Unmarshal(m, b)
}
func (m *AllNamesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllNamesResponse.Marshal(b, m, deterministic)
}
func (dst *AllNamesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllNamesResponse.Merge(dst, src)
}
func (m *AllNamesResponse) XXX_Size() int {
	return xxx_messageInfo_AllNamesResponse.Size(m)
}
func (m *AllNamesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllNamesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllNamesResponse proto.InternalMessageInfo

func (m *AllNamesResponse) GetAverageNames() []string {
	if m != nil {
		return m.AverageNames
	}
	return nil
}

func (m *AllNamesResponse) GetAveragePerDurationNames() []string {
	if m != nil {
		return m.AveragePerDurationNames
	}
	return nil
}

func (m *AllNamesResponse) GetCountNames() []string {
	if m != nil {
		return m.CountNames
	}
	return nil
}

func (m *AllNamesResponse) GetCountPerDurationNames() []string {
	if m != nil {
		return m.CountPerDurationNames
	}
	return nil
}

func (m *AllNamesResponse) GetSumNames() []string {
	if m != nil {
		return m.SumNames
	}
	return nil
}

func (m *AllNamesResponse) GetSumPerDurationNames() []string {
	if m != nil {
		return m.SumPerDurationNames
	}
	return nil
}

// Requesting a metric by name
type NameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameRequest) Reset()         { *m = NameRequest{} }
func (m *NameRequest) String() string { return proto.CompactTextString(m) }
func (*NameRequest) ProtoMessage()    {}
func (*NameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d05eb8469fe335f1, []int{2}
}
func (m *NameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameRequest.Unmarshal(m, b)
}
func (m *NameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameRequest.Marshal(b, m, deterministic)
}
func (dst *NameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameRequest.Merge(dst, src)
}
func (m *NameRequest) XXX_Size() int {
	return xxx_messageInfo_NameRequest.Size(m)
}
func (m *NameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NameRequest proto.InternalMessageInfo

func (m *NameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Responding to an average
type AverageResponse struct {
	Average              float64  `protobuf:"fixed64,1,opt,name=Average,proto3" json:"Average,omitempty"`
	N                    int64    `protobuf:"varint,2,opt,name=N,proto3" json:"N,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AverageResponse) Reset()         { *m = AverageResponse{} }
func (m *AverageResponse) String() string { return proto.CompactTextString(m) }
func (*AverageResponse) ProtoMessage()    {}
func (*AverageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d05eb8469fe335f1, []int{3}
}
func (m *AverageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AverageResponse.Unmarshal(m, b)
}
func (m *AverageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AverageResponse.Marshal(b, m, deterministic)
}
func (dst *AverageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AverageResponse.Merge(dst, src)
}
func (m *AverageResponse) XXX_Size() int {
	return xxx_messageInfo_AverageResponse.Size(m)
}
func (m *AverageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AverageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AverageResponse proto.InternalMessageInfo

func (m *AverageResponse) GetAverage() float64 {
	if m != nil {
		return m.Average
	}
	return 0
}

func (m *AverageResponse) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

// Responding to an average per duration
type AveragePerDurationResponse struct {
	Average              float64              `protobuf:"fixed64,1,opt,name=Average,proto3" json:"Average,omitempty"`
	N                    int64                `protobuf:"varint,2,opt,name=N,proto3" json:"N,omitempty"`
	Until                *timestamp.Timestamp `protobuf:"bytes,3,opt,name=Until,proto3" json:"Until,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AveragePerDurationResponse) Reset()         { *m = AveragePerDurationResponse{} }
func (m *AveragePerDurationResponse) String() string { return proto.CompactTextString(m) }
func (*AveragePerDurationResponse) ProtoMessage()    {}
func (*AveragePerDurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d05eb8469fe335f1, []int{4}
}
func (m *AveragePerDurationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AveragePerDurationResponse.Unmarshal(m, b)
}
func (m *AveragePerDurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AveragePerDurationResponse.Marshal(b, m, deterministic)
}
func (dst *AveragePerDurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AveragePerDurationResponse.Merge(dst, src)
}
func (m *AveragePerDurationResponse) XXX_Size() int {
	return xxx_messageInfo_AveragePerDurationResponse.Size(m)
}
func (m *AveragePerDurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AveragePerDurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AveragePerDurationResponse proto.InternalMessageInfo

func (m *AveragePerDurationResponse) GetAverage() float64 {
	if m != nil {
		return m.Average
	}
	return 0
}

func (m *AveragePerDurationResponse) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *AveragePerDurationResponse) GetUntil() *timestamp.Timestamp {
	if m != nil {
		return m.Until
	}
	return nil
}

type CountResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountResponse) Reset()         { *m = CountResponse{} }
func (m *CountResponse) String() string { return proto.CompactTextString(m) }
func (*CountResponse) ProtoMessage()    {}
func (*CountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d05eb8469fe335f1, []int{5}
}
func (m *CountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountResponse.Unmarshal(m, b)
}
func (m *CountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountResponse.Marshal(b, m, deterministic)
}
func (dst *CountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountResponse.Merge(dst, src)
}
func (m *CountResponse) XXX_Size() int {
	return xxx_messageInfo_CountResponse.Size(m)
}
func (m *CountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountResponse proto.InternalMessageInfo

func (m *CountResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CountPerDurationResponse struct {
	Count                int64                `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	Until                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=Until,proto3" json:"Until,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CountPerDurationResponse) Reset()         { *m = CountPerDurationResponse{} }
func (m *CountPerDurationResponse) String() string { return proto.CompactTextString(m) }
func (*CountPerDurationResponse) ProtoMessage()    {}
func (*CountPerDurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d05eb8469fe335f1, []int{6}
}
func (m *CountPerDurationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountPerDurationResponse.Unmarshal(m, b)
}
func (m *CountPerDurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountPerDurationResponse.Marshal(b, m, deterministic)
}
func (dst *CountPerDurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountPerDurationResponse.Merge(dst, src)
}
func (m *CountPerDurationResponse) XXX_Size() int {
	return xxx_messageInfo_CountPerDurationResponse.Size(m)
}
func (m *CountPerDurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountPerDurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountPerDurationResponse proto.InternalMessageInfo

func (m *CountPerDurationResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *CountPerDurationResponse) GetUntil() *timestamp.Timestamp {
	if m != nil {
		return m.Until
	}
	return nil
}

type SumResponse struct {
	Sum                  float64  `protobuf:"fixed64,1,opt,name=Sum,proto3" json:"Sum,omitempty"`
	N                    int64    `protobuf:"varint,2,opt,name=N,proto3" json:"N,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d05eb8469fe335f1, []int{7}
}
func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (dst *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(dst, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetSum() float64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *SumResponse) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

type SumPerDurationResponse struct {
	Sum                  float64              `protobuf:"fixed64,1,opt,name=Sum,proto3" json:"Sum,omitempty"`
	N                    int64                `protobuf:"varint,2,opt,name=N,proto3" json:"N,omitempty"`
	Until                *timestamp.Timestamp `protobuf:"bytes,3,opt,name=Until,proto3" json:"Until,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SumPerDurationResponse) Reset()         { *m = SumPerDurationResponse{} }
func (m *SumPerDurationResponse) String() string { return proto.CompactTextString(m) }
func (*SumPerDurationResponse) ProtoMessage()    {}
func (*SumPerDurationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d05eb8469fe335f1, []int{8}
}
func (m *SumPerDurationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumPerDurationResponse.Unmarshal(m, b)
}
func (m *SumPerDurationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumPerDurationResponse.Marshal(b, m, deterministic)
}
func (dst *SumPerDurationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumPerDurationResponse.Merge(dst, src)
}
func (m *SumPerDurationResponse) XXX_Size() int {
	return xxx_messageInfo_SumPerDurationResponse.Size(m)
}
func (m *SumPerDurationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumPerDurationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumPerDurationResponse proto.InternalMessageInfo

func (m *SumPerDurationResponse) GetSum() float64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *SumPerDurationResponse) GetN() int64 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *SumPerDurationResponse) GetUntil() *timestamp.Timestamp {
	if m != nil {
		return m.Until
	}
	return nil
}

func init() {
	proto.RegisterType((*AllNamesRequest)(nil), "api.AllNamesRequest")
	proto.RegisterType((*AllNamesResponse)(nil), "api.AllNamesResponse")
	proto.RegisterType((*NameRequest)(nil), "api.NameRequest")
	proto.RegisterType((*AverageResponse)(nil), "api.AverageResponse")
	proto.RegisterType((*AveragePerDurationResponse)(nil), "api.AveragePerDurationResponse")
	proto.RegisterType((*CountResponse)(nil), "api.CountResponse")
	proto.RegisterType((*CountPerDurationResponse)(nil), "api.CountPerDurationResponse")
	proto.RegisterType((*SumResponse)(nil), "api.SumResponse")
	proto.RegisterType((*SumPerDurationResponse)(nil), "api.SumPerDurationResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReporterClient is the client API for Reporter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReporterClient interface {
	AllNames(ctx context.Context, in *AllNamesRequest, opts ...grpc.CallOption) (*AllNamesResponse, error)
	Average(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*AverageResponse, error)
	AveragePerDuration(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*AveragePerDurationResponse, error)
	Count(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*CountResponse, error)
	CountPerDuration(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*CountPerDurationResponse, error)
	Sum(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*SumResponse, error)
	SumPerDuration(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*SumPerDurationResponse, error)
}

type reporterClient struct {
	cc *grpc.ClientConn
}

func NewReporterClient(cc *grpc.ClientConn) ReporterClient {
	return &reporterClient{cc}
}

func (c *reporterClient) AllNames(ctx context.Context, in *AllNamesRequest, opts ...grpc.CallOption) (*AllNamesResponse, error) {
	out := new(AllNamesResponse)
	err := c.cc.Invoke(ctx, "/api.Reporter/AllNames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterClient) Average(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*AverageResponse, error) {
	out := new(AverageResponse)
	err := c.cc.Invoke(ctx, "/api.Reporter/Average", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterClient) AveragePerDuration(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*AveragePerDurationResponse, error) {
	out := new(AveragePerDurationResponse)
	err := c.cc.Invoke(ctx, "/api.Reporter/AveragePerDuration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterClient) Count(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, "/api.Reporter/Count", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterClient) CountPerDuration(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*CountPerDurationResponse, error) {
	out := new(CountPerDurationResponse)
	err := c.cc.Invoke(ctx, "/api.Reporter/CountPerDuration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterClient) Sum(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/api.Reporter/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterClient) SumPerDuration(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*SumPerDurationResponse, error) {
	out := new(SumPerDurationResponse)
	err := c.cc.Invoke(ctx, "/api.Reporter/SumPerDuration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReporterServer is the server API for Reporter service.
type ReporterServer interface {
	AllNames(context.Context, *AllNamesRequest) (*AllNamesResponse, error)
	Average(context.Context, *NameRequest) (*AverageResponse, error)
	AveragePerDuration(context.Context, *NameRequest) (*AveragePerDurationResponse, error)
	Count(context.Context, *NameRequest) (*CountResponse, error)
	CountPerDuration(context.Context, *NameRequest) (*CountPerDurationResponse, error)
	Sum(context.Context, *NameRequest) (*SumResponse, error)
	SumPerDuration(context.Context, *NameRequest) (*SumPerDurationResponse, error)
}

func RegisterReporterServer(s *grpc.Server, srv ReporterServer) {
	s.RegisterService(&_Reporter_serviceDesc, srv)
}

func _Reporter_AllNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).AllNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Reporter/AllNames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).AllNames(ctx, req.(*AllNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporter_Average_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).Average(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Reporter/Average",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).Average(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporter_AveragePerDuration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).AveragePerDuration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Reporter/AveragePerDuration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).AveragePerDuration(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporter_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Reporter/Count",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).Count(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporter_CountPerDuration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).CountPerDuration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Reporter/CountPerDuration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).CountPerDuration(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporter_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Reporter/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).Sum(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reporter_SumPerDuration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServer).SumPerDuration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Reporter/SumPerDuration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServer).SumPerDuration(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Reporter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Reporter",
	HandlerType: (*ReporterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllNames",
			Handler:    _Reporter_AllNames_Handler,
		},
		{
			MethodName: "Average",
			Handler:    _Reporter_Average_Handler,
		},
		{
			MethodName: "AveragePerDuration",
			Handler:    _Reporter_AveragePerDuration_Handler,
		},
		{
			MethodName: "Count",
			Handler:    _Reporter_Count_Handler,
		},
		{
			MethodName: "CountPerDuration",
			Handler:    _Reporter_CountPerDuration_Handler,
		},
		{
			MethodName: "Sum",
			Handler:    _Reporter_Sum_Handler,
		},
		{
			MethodName: "SumPerDuration",
			Handler:    _Reporter_SumPerDuration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_d05eb8469fe335f1) }

var fileDescriptor_api_d05eb8469fe335f1 = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x4d, 0xea, 0x75, 0xb4, 0xb7, 0x83, 0x95, 0xcb, 0x06, 0x51, 0x10, 0xac, 0x58, 0x42, 0xaa,
	0x84, 0x48, 0xa7, 0x8d, 0x07, 0xf6, 0x58, 0x01, 0x0f, 0xbc, 0x54, 0xc8, 0x85, 0x0f, 0x48, 0x25,
	0x53, 0x05, 0x35, 0x75, 0x48, 0xec, 0x7d, 0x09, 0xbf, 0xc1, 0x3f, 0xa2, 0x5e, 0x27, 0x69, 0x93,
	0x98, 0x69, 0x7b, 0xf3, 0x3d, 0x3e, 0xe7, 0xda, 0x3e, 0xe7, 0x1a, 0x86, 0x71, 0x96, 0x44, 0x59,
	0xae, 0xb4, 0x42, 0x16, 0x67, 0x49, 0x78, 0xb1, 0x56, 0x6a, 0xbd, 0x91, 0x33, 0x82, 0x56, 0xe6,
	0xe7, 0x4c, 0x27, 0xa9, 0x2c, 0x74, 0x9c, 0x66, 0x96, 0xc5, 0x9f, 0xc2, 0xe9, 0x7c, 0xb3, 0x59,
	0xc4, 0xa9, 0x2c, 0x84, 0xfc, 0x6d, 0x64, 0xa1, 0xf9, 0x9f, 0x1e, 0x8c, 0xf7, 0x58, 0x91, 0xa9,
	0x6d, 0x21, 0x91, 0xc3, 0xc9, 0xfc, 0x56, 0xe6, 0xf1, 0x5a, 0x12, 0x1e, 0xf8, 0x13, 0x36, 0x1d,
	0x8a, 0x06, 0x86, 0x1f, 0xe1, 0x45, 0x59, 0x7f, 0x93, 0xf9, 0x67, 0x93, 0xc7, 0x3a, 0x51, 0x5b,
	0x4b, 0xef, 0x11, 0xfd, 0x7f, 0xdb, 0xf8, 0x1a, 0xe0, 0x93, 0x32, 0x5b, 0x6d, 0xc9, 0x8c, 0xc8,
	0x07, 0x08, 0x7e, 0x80, 0x73, 0xaa, 0x3a, 0x7d, 0x8f, 0x88, 0xea, 0xde, 0xc4, 0x10, 0x06, 0x4b,
	0x93, 0x5a, 0x62, 0x9f, 0x88, 0x75, 0x8d, 0x97, 0xf0, 0x6c, 0x69, 0xd2, 0x4e, 0xbf, 0x63, 0xa2,
	0xb9, 0xb6, 0xf8, 0x1b, 0x18, 0xed, 0x16, 0xa5, 0x4b, 0x88, 0x70, 0xb4, 0x2b, 0x03, 0x7f, 0xe2,
	0x4f, 0x87, 0x82, 0xd6, 0xfc, 0x06, 0x4e, 0xcb, 0x17, 0xd6, 0xbe, 0x05, 0xf0, 0xa8, 0x84, 0x88,
	0xe9, 0x8b, 0xaa, 0xc4, 0x13, 0xf0, 0x17, 0x41, 0x6f, 0xe2, 0x4f, 0x99, 0xf0, 0x17, 0xfc, 0x16,
	0xc2, 0xae, 0x39, 0x0f, 0xed, 0x82, 0x97, 0xd0, 0xff, 0xb1, 0xd5, 0xc9, 0x26, 0x60, 0x13, 0x7f,
	0x3a, 0xba, 0x0a, 0x23, 0x1b, 0x7f, 0x54, 0xc5, 0x1f, 0x7d, 0xaf, 0xe2, 0x17, 0x96, 0xc8, 0xdf,
	0xc2, 0x63, 0x32, 0xaf, 0x3e, 0xea, 0x0c, 0xfa, 0x04, 0xd0, 0x41, 0x4c, 0xd8, 0x82, 0xaf, 0x20,
	0x68, 0x7b, 0x7c, 0xb7, 0x62, 0x7f, 0x95, 0xde, 0x7d, 0xaf, 0xf2, 0x1e, 0x46, 0x4b, 0x93, 0xd6,
	0x6d, 0xc7, 0xc0, 0x96, 0x26, 0x2d, 0xdf, 0xbb, 0x5b, 0xb6, 0x1c, 0xfb, 0x05, 0xcf, 0x9b, 0x31,
	0xdd, 0x57, 0xf9, 0x70, 0x97, 0xae, 0xfe, 0x32, 0x18, 0x08, 0x99, 0xa9, 0x5c, 0xcb, 0x1c, 0x6f,
	0x60, 0x50, 0x7d, 0x0f, 0x3c, 0x8b, 0x76, 0x1f, 0xae, 0xf5, 0x83, 0xc2, 0xf3, 0x16, 0x6a, 0xef,
	0xc5, 0x3d, 0xbc, 0xae, 0x73, 0xc4, 0x31, 0x71, 0x0e, 0x26, 0x2a, 0x2c, 0x7b, 0x35, 0x07, 0x88,
	0x7b, 0xf8, 0x15, 0xb0, 0x3b, 0x1a, 0x0e, 0xfd, 0xc5, 0xa1, 0xde, 0xe1, 0x0b, 0xf7, 0x70, 0x56,
	0x46, 0xe5, 0x50, 0x23, 0x21, 0x8d, 0x59, 0xe0, 0x1e, 0x7e, 0x81, 0x71, 0x3b, 0x77, 0x87, 0xf6,
	0xd5, 0x5e, 0xeb, 0x3e, 0xf7, 0x1d, 0x25, 0xe2, 0x50, 0x5a, 0xe4, 0x20, 0x76, 0xee, 0xe1, 0x1c,
	0x9e, 0x34, 0x83, 0x75, 0xe8, 0x5e, 0x56, 0x3a, 0xe7, 0x79, 0xab, 0x63, 0x8a, 0xf2, 0xfa, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xd0, 0xf0, 0x79, 0xe3, 0x0f, 0x05, 0x00, 0x00,
}
